### ISSUE TITLE
Incorrect link on home page: https://h3rald.com/10-more-programming-languages/  

### ISSUE THREAD

**Issue by Gavin-Holt** [h3rald/h3rald#66]
Hi

I was trying to get to 
      https://h3rald.com/articles/10-more-programming-languages/
but the link on your home page points to 
      https://h3rald.com/10-more-programming-languages/ 
and fails - reverting to loading the home page.

I enjoyed reading both language lists and plan to play with min.

Kind Regards Gavin Holt

**Comment by h3rald** [comment]
Well spotted! Fixed, thanks!
